openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Admin API"
  description: "Administration API for managing org units and sensors"
servers:
  - url: http://localhost:8080

paths:
  /OrgTreeEdges:
    post:
      summary: "Create org tree edge"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrgTreeEdge"
      responses:
        200:
          description: "OK, org tree edge entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgTreeEdge"
        404:
          description: "Org tree node not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Can't add org tree edge"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete org tree edge"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrgTreeEdge"
      responses:
        200:
          description: "OK, deleted org tree edge entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgTreeEdge"
        404:
          description: "Org tree edge not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /OrgTreeNodes:
    post:
      summary: "Create org tree node"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrgTreeNode"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgTreeNode"
        404:
          description: "Object not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Can't add org tree node"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /OrgTreeNodes/{OrgTreeNode_id}:
    get:
      summary: "Read org tree node"
      parameters:
        - name: "OrgTreeNode_id"
          description: "The unique identifier of org tree node"
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/OrgTreeNode_id"
      responses:
        200:
          description: "OK, org tree node entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgTreeNode"
        404:
          description: "Org tree node not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete org tree node"
      parameters:
        - name: "OrgTreeNode_id"
          description: "The unique identifier of org tree node"
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/OrgTreeNode_id"
      responses:
        200:
          description: "OK, deleted org tree node entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgTreeNode"
        404:
          description: "Org tree node not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /SensorTypes:
    post:
      summary: "Create new sensor type"
      requestBody:
        description: "Sensor type information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SensorType"
      responses:
        200:
          description: "OK, sensor type entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SensorType"
        500:
          description: "Can't add sensor type"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /Sensors:
    post:
      summary: "Create new sensor"
      requestBody:
        description: "Sensor data"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sensor"
      responses:
        200:
          description: "OK, sensor entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sensor"
        500:
          description: "Can't add sensor"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /Sensors/{Sensor_id}/CH_Data:
    parameters:
      - name: "Sensor_id"
        description: "The unique identifier of the sensor"
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Sensor_id"
    get:
      summary: "Read sensor data stored in ClickHouse"
      responses:
        200:
          description: "OK, sensor data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CH_Data"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /Sensors/{Sensor_id}:
    parameters:
      - name: "Sensor_id"
        description: "The unique identifier of the sensor"
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Sensor_id"
    get:
      summary: "Read sensor"
      responses:
        200:
          description: "OK, sensor entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sensor"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: "Redefine sensor properties"
      requestBody:
        description: "Sensor information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Sensor"
      responses:
        200:
          description: "OK, updated sensor entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sensor"
        404:
          description: "Sensor not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete sensor"
      responses:
        200:
          description: "OK, deleted sensor entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sensor"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /OrgUnits:
    post:
      summary: "Create org tree unit"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrgUnit"
      responses:
        200:
          description: "OK, organization unit entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgUnit"
        500:
          description: "Can't add organization unit"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /OrgUnits/{OrgUnit_id}:
    get:
      summary: "Read organization unit"
      parameters:
        - name: "OrgUnit_id"
          description: "The unique identifier of organization unit"
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/OrgUnit_id"
      responses:
        200:
          description: "OK, organization unit entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgUnit"
        404:
          description: "Organization unit not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: "Delete organization unit"
      parameters:
        - name: "OrgUnit_id"
          description: "The unique identifier of organization unit"
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/OrgUnit_id"
      responses:
        200:
          description: "OK, deleted organization unit entry"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrgUnit"
        404:
          description: "Organization unit not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    CH_Data:
      description: "ClickHouse data"
      type: "array"
      items:
        type: "array"
        items:
          type: "number"
          format: "double"

    Date:
      description: "Date of removal"
      type: "string"
      format: "date"

    OrgTreeNode_id:
      description: "The unique identifier of an organization tree node"
      type: "integer"
      format: "int64"

    OrgTreeEdge_id:
      description: "The unique identifier of an organization tree edge"
      type: "integer"
      format: "int64"

    OrgTreeEdge:
      type: "object"
      required:
        - "id"
        - "id_u"
        - "id_v"
        - "parent"
        - "date"
      properties:
        id:
          $ref: "#/components/schemas/OrgTreeEdge_id"
        id_u:
          $ref: "#/components/schemas/OrgTreeNode_id"
        id_v:
          $ref: "#/components/schemas/OrgTreeNode_id"
        parent:
          description: "true - u is parent of v"
          type: "boolean"
          format: "bool"
        date:
          $ref: "#/components/schemas/Date"

    OrgTreeNode:
      type: "object"
      required:
        - "id"
        - "type"
        - "object_id"
        - "date"
      properties:
        id:
          $ref: "#/components/schemas/OrgTreeNode_id"
        type:
          description: '"Sensor" or "OrgUnit"'
          type: string
        object_id:
          description: "OrgUnit_id or Sensor_id"
          type: "integer"
          format: "int64"
        date:
          $ref: "#/components/schemas/Date"

    OrgUnit_id:
      description: "The unique identifier of an organization unit"
      type: "integer"
      format: "int64"

    OrgUnit:
      type: "object"
      required:
        - "id"
        - "name"
        - "type"
        - "json"
        - "date"
      properties:
        id:
          $ref: "#/components/schemas/OrgUnit_id"
        name:
          type: "string"
        type:
          type: "string"
        json:
          type: "string"
        date:
          $ref: "#/components/schemas/Date"

    Sensor_id:
      description: "The unique identifier of a sensor"
      type: "integer"
      format: "int64"

    SensorType_id:
      description: "The unique identifier ot a sensor type"
      type: "integer"
      format: "int64"

    CH_Sensor_id:
      description: "The unique identifier of ClickHouse sensor table"
      type: "integer"
      format: "int64"

    SensorType:
      type: "object"
      required:
        - "id"
        - "freq"
        - "dim"
        - "info"
      properties:
        id:
          $ref: "#/components/schemas/SensorType_id"
        freq:
          type: "integer"
          format: "int64"
        dim:
          type: "integer"
          format: "int64"
        info:
          type: "string"

    Sensor:
      type: "object"
      required:
        - "id"
        - "type_id"
        - "ch_id"
        - "date"
      properties:
        id:
          $ref: "#/components/schemas/Sensor_id"
        type_id:
          $ref: "#/components/schemas/SensorType_id"
        chid:
          $ref: "#/components/schemas/CH_Sensor_id"
        date:
          $ref: "#/components/schemas/Date"

    Error:
      type: "object"
      required:
        - "message"
      properties:
        message:
          description: "A human readable error message"
          type: "string"
